### ISSUE TITLE
Changing the application name 

### ISSUE THREAD

**Issue by InstinctTheDevil** [KeyAuth/KeyAuth-Source-Code#100]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**

**Describe the bug**
 An error pops up when renaming your application, saying "Application Renamed Failed!".

The application will still rename, tho it shows that error.

**Steps To Reproduce**
Rename your application

**Expected behavior**
Rename the app and then select it?

**Screenshots**
https://cdn.discordapp.com/attachments/939731558334595102/1005619121817403432/firefox_MzGtV19kgW.png

**Comment by mazk5145** [comment]
Okay lemme see!

**Comment by mazk5145** [comment]
Okay, Thanks for reporting this issue, We will take look at it.

**Best Regards:
KeyAuth Head Admin / Developer - mazkdevf**

**Comment by mazk5145** [comment]
![image](https://user-images.githubusercontent.com/79049205/183285087-4cb3a5f3-faa1-4784-8df6-6f87a2a36d8c.png)
img uploud

**Comment by mazk5145** [comment]
Oh it works, but just error message pops up instead of success message.

**Comment by mazk5145** [comment]
This will fix this. **https://github.com/KeyAuth/KeyAuth-Source-Code/pull/101**
