### ISSUE TITLE
Changing App-Secret deleting WebLoader Buttons

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#102]
If i change my app-secret my buttons from the web loader got deleted and i need to recreate it

**Comment by mazk5145** [comment]
Hello, Thanks for reporting this issue to us. 

We will take look at it soon and we will fix the issue.

Best Regards
KeyAuth Head Admin / Developer - mazkdev

**Comment by wnelson03** [comment]
Fixed, thanks for making us aware.
