### ISSUE TITLE
New ReadMe Image

### ISSUE THREAD

**Issue by mazkdevf** [KeyAuth/KeyAuth-Source-Code#105]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**
yes

**Describe the suggestion**
New Dev Branch Image of the New Dashboard

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

https://i.imgur.com/rige1nM.png

[![Screenshot](https://i.imgur.com/rige1nM.png)](https://keyauth.win)

**Comment by wnelson03** [comment]
ty changed. fyi next time you can change yourself. you're better at design than I am so you know how to make README's and such look the best.

**Comment by mazkdevf** [comment]
> ty changed. fyi next time you can change yourself. you're better at design than I am so you know how to make README's and such look the best.

Thanks
