### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by Sato-Isolated** [KeyAuth/KeyAuth-Source-Code#106]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**

**Describe the bug**
*Hi I have a problem with the logs they appear with the webhook but not in the panel and I would like to know also how to increase the size of the webhook logs*

**Comment by Pinguu-dev** [comment]
> **I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**
> 
> **Describe the bug** _Hi I have a problem with the logs they appear with the webhook but not in the panel and I would like to know also how to increase the size of the webhook logs_

I have the same problem

**Comment by wnelson03** [comment]
This is how it's supposed to be. If you specify Discord webhook, then it doesn't store in the KeyAuth database also as that would be redundant to save to two places.

What do you mean by "increase the size of the webhook logs"?

**Comment by Sato-Isolated** [comment]
If the string is too big, the Discord webhook is not received.

So is there a default value to modify to receive a webhook with a bigger string or is it a limit imposed by Discord?

**Comment by wnelson03** [comment]
> If the string is too big, the Discord webhook is not received.
> 
> So is there a default value to modify to receive a webhook with a bigger string or is it a limit imposed by Discord?

Yes, 256 characters is limit for embed title (what `KeyAuthApp.log()` function uses)

However, you can create webhook on KeyAuth dashboard and then use this code instead https://github.com/KeyAuth/KeyAuth-CSHARP-Example/blob/42444be848434d6758e4f987c877860693b5e0d2/Console/Program.cs#L189

Then limit is expanded to 2000 characters.
