### ISSUE TITLE
Issue with users!

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#107]
I now have the problem with two of my customers that I cannot reset the users. Every time I try, Keyauth tells me that the reset failed. This happens more and more often and I have to delete the entire user.

**Comment by wnelson03** [comment]
Send the username of the user you're having trouble resetting and the name of the application the user belongs to.

**Comment by wnelson03** [comment]
Assuming this is resolved. Please try again and if it's still occurring please send video showing the issue.

**Comment by Pinguu-dev** [comment]
Problem is there again... Name of application GTX745, name of the user "Atropy".

If i try to reset it over Discord-Bot the discord bot tells me: 
"Your seller key is most likely invalid. Change your seller key with /setseller command." (all other users work)

If i try it directly in the webpanel it say "Failed to reset user!"

**Comment by Pinguu-dev** [comment]
@wnelson03

**Comment by Pinguu-dev** [comment]
@wnelson03

**Comment by wnelson03** [comment]
@Pinguu-dev the HWID of the user with username `Atropy` is null, so trying to reset a HWID that is already reset is going to give error message.

**Comment by Pinguu-dev** [comment]
I got again a user with it: xtyaa

(but the null does not allow him to login)

**Comment by wnelson03** [comment]
> I got again a user with it: xtyaa
> 
> (but the null does not allow him to login)

What's the error message the user `xtyaa` gets when trying to login?

That user should definitely be able to login. When the HWID column is NULL, KeyAuth is supposed to update it to the HWID provided and allow a successful login.

**Comment by Pinguu-dev** [comment]
Works fine now. It was a issue with this user, thank you!
