### ISSUE TITLE
Save license key / user data

### ISSUE THREAD

**Issue by RoksanaKregiel** [KeyAuth/KeyAuth-Source-Code#108]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
simple save user login / pass or license key

**Comment by wnelson03** [comment]
This is something you can do in your loader. We're not going to do for you. You can do a simple search online to learn how to write data to a file and check if file exists and then read data from a file.
