### ISSUE TITLE
Web-Loader Button does not show up

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#109]
Hey there, I'm back with the next issue.

My Web-Loader Button does not show up after web-login - It stay on "Download".

**Comment by Pinguu-dev** [comment]
It's not a enhancement its a bug - Sorry 🤣

**Comment by wnelson03** [comment]
Yeah I explained this on Discord

![F81AD81D-B684-488C-B342-D02769BA3305](https://user-images.githubusercontent.com/83034852/186645489-5893d710-635f-4462-bb7d-5c6a9a96ff92.png)

please download the latest library_x64.lib file here https://github.com/KeyAuth/KeyAuth-CPP-Example/blob/e9e3cd97621fbca7ffb2ea56f9446689d9303682/library_x64.lib
