### ISSUE TITLE
manage-accs deleted?

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#111]
Hey there!

Got "manage-accs" deleted? I see in my self hosting only: (also webloader)
![image](https://user-images.githubusercontent.com/72171280/190867899-1a48a090-05a6-403d-b8f1-52dd62094c1e.png)

Thanks

**Comment by wnelson03** [comment]
You can buy access to the other files (SellerAPI, Reseller API, customer panel, reseller dashboard) here https://shop.keyauth.cc/product/keyauth-enterprise

Would be much appreciated. Helps support our costs and pay for our time. Plus you with buying KeyAuth Enterprise, you get setup help from me, and a tutorial video on how to host KeyAuth for 100% free forever, and it's secure and fast. The company offering the free cloud computing is very reputable.
