### ISSUE TITLE
Bug Choose an App Issues

### ISSUE THREAD

**Issue by IzE-PewPewPew** [KeyAuth/KeyAuth-Source-Code#15]
After login and create an app , then when we re-login again it's always no app in db !

**Comment by wnelson03** [comment]
Apologies, fix will be uploaded soon. All you need to do is set columns `dayproduct`, `weekproduct`, `monthproduct`, and `lifetimeproduct` in apps table to default NULL

**Comment by wnelson03** [comment]
Fixed SQL file too if you didn't figure it out, apologies about that
