### ISSUE TITLE
 Human Check Failed!

### ISSUE THREAD

**Issue by ByYasin** [KeyAuth/KeyAuth-Source-Code#18]
It gives the following error when registering from the Register section. What is the problem? Same with all usernames and passwords?

---> Human Check Failed!

**Comment by wnelson03** [comment]
That means you're too suspicous for the Google recaptcha. You can try changing the score on https://github.com/KeyAuth/KeyAuth-Source-Code/blob/main/register/index.php#L92 to 0.8 from 0.5

**Comment by ByYasin** [comment]
I changed it, no solution?

**Comment by wnelson03** [comment]
Try putting
```php
echo $recaptcha->score;
```
on the line above the if statement, and then see what score it prints out. It should be a score between 0.0 and 1.0. Whatever the score is, make sure the if statement allows you to sign up. Your score is most likely under 0.5, so if it's 0.3 for example, change the score it checks for to allow you to sign up.

**Comment by ByYasin** [comment]
0.0 
I changed it to and it works now.

**Comment by ByYasin** [comment]
but even though I have made my role partition from the database as a seller, it still remains as tester, does not change, is there a solution?

**Comment by wnelson03** [comment]
You need to change the expiry column of your account. Change to a year in the future or whatever. Use https://unixtimestamp.com to create a timestamp which is a 10-digit number. Copy that and update the expires column

**Comment by ByYasin** [comment]
okay thanks.

**Comment by ByYasin** [comment]
By default, when you create a membership, it expires "NULL". 1970 year.

**Comment by wnelson03** [comment]
I'm aware, update expires to timestamp in the future
