### ISSUE TITLE
#1231 - Variable 'character_set_client' can't be set to the value of 'NULL'

### ISSUE THREAD

**Issue by SamuelBostock** [KeyAuth/KeyAuth-Source-Code#2]
When trying to import the SQL, the following error is produced

SQL query:

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */
MySQL said: Documentation

#1231 - Variable 'character_set_client' can't be set to the value of 'NULL'

**Comment by wnelson03** [comment]
Try the new file https://github.com/KeyAuth/KeyAuth-Source-Code/blob/main/db_structure.sql

I included the configuration settings this time.

**Comment by wnelson03** [comment]
That should've fixed your issue
