### ISSUE TITLE
can't register or login in localhot

### ISSUE THREAD

**Issue by imedox** [KeyAuth/KeyAuth-Source-Code#20]
hi,
i install this in localhost with wampserver, wen i try to creat account nothing happen, can't register or login in localhot

**Comment by wnelson03** [comment]
Does it show an error? Did you setup database too?

**Comment by imedox** [comment]
no it not show any errors, just it refresh the same page

**Comment by wnelson03** [comment]
Show errors by putting
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
After line 3 of register page

**Comment by HjInYoMaMa** [comment]
i got the same problem all is setup correctly but cannot log in and even register page just refreshes and then nothing happen.

**Comment by wnelson03** [comment]
not sure what to tell you. I'm using the same code and it's working locally with XAMPP

**Comment by HjInYoMaMa** [comment]
Like when i try to log in or register then it just refreshes page

**Comment by imedox** [comment]
the sam as @HjInYoMaMa

**Comment by imedox** [comment]
ok it work now with XAMPP, need change the DB name to "keyauth" nothing else, let test with wampserver

**Comment by wnelson03** [comment]
Alright yeah you can change db name in connection.php if you want, glad you figured it out.
