### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Mochongli** [KeyAuth/KeyAuth-Source-Code#21]
One click encryption like the one in this video
https://www.maposafe.com/index/help/quickstart

**Comment by wnelson03** [comment]
Is this file encryption? In that case, we currently encrypt the response for file downloads

**Comment by YMY1666527646** [comment]
I've added discord webhook
But he is always ，ERROR: Could not connect. No such file or directory
ERROR: Could not connect. No such file or directory

**Comment by YMY1666527646** [comment]
$link = mysqli_connect("localhost", "root", "", "keyauth");
localhost=MySQL server host address？
root=MySQL user name？
keyauth=MySQL username and password？

**Comment by wnelson03** [comment]
You should most likely leave localhost how it is, change root to database username.  change the blank string (third parameter) to your database password. And then change keyauth to database name

**Comment by YMY1666527646** [comment]
> 数据库用户名

For example ("localhost", "root", "keyauth");
("I'm ip1.2.3.4", "I'm the database user name epiz_uuxxxxx", "I'm the password XXXXXX", "I'm the database name epiz_uuxxxxx");
If so, I'm not very familiar with PHP

**Comment by YMY1666527646** [comment]
I still have the wrong connection

$link = mysqli_connect("XXXXXX", "epiz_30602787", "Jo6KAnY7Zzp", "epiz_30602787_keyauth","3306");

**Comment by YMY1666527646** [comment]
- I've connected successfully ，However, entering admin management is like this 
![keyadmin](https://user-images.githubusercontent.com/84628110/146333416-2bf65566-d162-4a80-a524-c243dd7a8bcd.png)
d

**Comment by YMY1666527646** [comment]
![ergister](https://user-images.githubusercontent.com/84628110/146340578-5bd3114f-c0fe-4ae4-9acd-1d30e93e1e18.png)
![human check failed！](https://user-images.githubusercontent.com/84628110/146340587-908d4b00-2763-4fff-b4f0-281d4c4bce62.png)
Google man-machine verification and loading error

**Comment by wnelson03** [comment]
Go to your login/index.php and edit the recaptcha score on line 94 to 0.0. For the admin page, go to database and change the isadmin column to 1

**Comment by YMY1666527646** [comment]
Thank you very much for your guidance and help. Thank you

**Comment by wnelson03** [comment]
Glad I could resolve your issue.
