### ISSUE TITLE
No tables in database? He didn't succeed. What should I do? Create table manually?

### ISSUE THREAD

**Issue by YMY1666527646** [KeyAuth/KeyAuth-Source-Code#23]
Table 'epiz_30602787_keyauth.accounts' doesn't exist

**Comment by YMY1666527646** [comment]
Do I need to use phpMyAdmin changes SQL, and DB_ structure. SQL import and execute

**Comment by wnelson03** [comment]
you need to copy all text from https://github.com/KeyAuth/KeyAuth-Source-Code/blob/main/db_structure.sql and go to SQL tab of phpMyAdmin and paste then enter

**Comment by YMY1666527646** [comment]
I can't find isadmin in the database

**Comment by wnelson03** [comment]
Yeah it's `owner` not isadmin. I mispelled. You could've just looked at the code though and you would've seen the correct column name. needs to be set to 1 to have admin

![image](https://user-images.githubusercontent.com/83034852/146656991-4cd51919-2106-41d7-8f89-4269f2d35296.png)

**Comment by YMY1666527646** [comment]
> Yeah it's `admin` not isadmin. I mispelled. You could've just looked at the code though and you would've seen the correct column name. needs to be set to 1 to have admin
> 
> ![image](https://user-images.githubusercontent.com/83034852/146656991-4cd51919-2106-41d7-8f89-4269f2d35296.png)

Thank you very much. I found and set 1 in the database. My own account is the administrator
![01B9E6B9-0D06-45DE-B3AF-7342BA0AFA0C](https://user-images.githubusercontent.com/84628110/146657234-86f34ac8-847e-458d-987c-44b5458ffea4.jpeg)


Can I change this page to another language？

![EAA3F22D-4CF0-4BD8-825B-5C8A71DD85D3](https://user-images.githubusercontent.com/84628110/146657277-df19634c-01a4-41c4-96cc-6a38c7509d39.jpeg)

**Comment by wnelson03** [comment]
Yeah or you could use browser extension to change language, I think that's what most of our users do

**Comment by YMY1666527646** [comment]
Can I modify it in the source?
I can't see these strings in user PHP
I want to use it alone, keyauth
Is my account in tester subscription status?

**Comment by YMY1666527646** [comment]
> Yeah or you could use browser extension to change language, I think that's what most of our users do

Hello,I set up keyauth and add keyauth CPP connection，It doesn't seem to connect
This is the keyauth I built：keyauth.epizy.com
![my key](https://user-images.githubusercontent.com/84628110/146754139-6fda0930-0ee9-4ee6-90f0-2f5e27607850.png)
my keyauth -cpp
------------------------------------------------------------------------------------------------
I use keyauth.com
keyauth；Can connect successfully 

As shown below：
![keyauth com](https://user-images.githubusercontent.com/84628110/146754679-1ba9d06e-698f-4d2a-94d6-0e9f4f9bc9c8.png)
Please help me

**Comment by wnelson03** [comment]
The correct URL is http://keyauth.epizy.com/api/1.0/

You’re probably trying to do https:// which doesn’t work with epizy 

please stop asking questions that don’t have to do with KeyAuth, thanks. We only assist with issues with KeyAuth code. Not random issues that you should already know how to solve

**Comment by YMY1666527646** [comment]
> The correct URL is http://keyauth.epizy.com/api/1.0/
> 
> You’re probably trying to do https:// which doesn’t work with epizy
> 
> please stop asking questions that don’t have to do with KeyAuth, thanks. We only assist with issues with KeyAuth code. Not random issues that you should already know how to solve

I'm sorry. I'm stupid
