### ISSUE TITLE
Keys aren't copying to the clipboard & key won't show up at the top when generated

### ISSUE THREAD

**Issue by notsoeac** [KeyAuth/KeyAuth-Source-Code#24]
As said in the title

**Comment by mazk5145** [comment]
Hello notsoeac, I saw your issue. It will only copy the first key that you generated.

**Comment by wnelson03** [comment]
> Hello notsoeac, I saw your issue. It will only copy the first key that you generated.

No, the key is only copied if you made one license key. It doesn't matter if it's the 100th key you've made, as long as you only generate one key, it'll copy to clipboard. If you generate more than one key, it'll show the keys in a box that you can copy from.

By default, I believe the keys are sorted by their alphanumeric contents. Though, if you click on the date generated column, you can change it such that it sorts by date generated rather.

**Comment by wnelson03** [comment]
Also, some browsers such as Firefox disable the website's ability to copy to clipboard by default. So if you're only generating one key and it's not copying to clipboard, make sure you have set the browser to allow that functionality.
