### ISSUE TITLE
HWID is not detected.

### ISSUE THREAD

**Issue by Mezantrop74** [KeyAuth/KeyAuth-Source-Code#26]
For the test, I ran it on various OS.
Everything works correctly on windows.
I have Linux installed on a virtual machine and it is not detected in it - writes None.

**Comment by mdp18** [comment]
read the source code of the API wrapper. It states if its windows it'll grab the HWID, else it'll return None.

**Comment by wnelson03** [comment]
Thanks max, I've committed that to the Python example.
