### ISSUE TITLE
blank page and cant create a application

### ISSUE THREAD

**Issue by kingsman12212** [KeyAuth/KeyAuth-Source-Code#3]
![image](https://user-images.githubusercontent.com/80263858/123374503-d5029080-d5a4-11eb-9a50-80a3062c6373.png)
![image](https://user-images.githubusercontent.com/80263858/123374653-11ce8780-d5a5-11eb-9931-a60bd5e5c532.png)

**Comment by kingsman12212** [comment]
What i need to do ?

**Comment by kingsman12212** [comment]
Do i need some type of api key or stuff plz help me

**Comment by kingsman12212** [comment]
@wnelson03 Can u help help me with that

**Comment by wnelson03** [comment]
Try going to phpmyadmin and then going to apps, structure tab, then click change button on sellixsecret and set default to null and save

**Comment by kingsman12212** [comment]
![image](https://user-images.githubusercontent.com/80263858/123461867-3ce9c300-d607-11eb-9c79-7ad3578d4a9a.png)
their is no sellixsecret option

**Comment by wnelson03** [comment]
Click on apps, then click on structure, then go to sellixsecret and press change. Then click null and save. 

Video: https://files.catbox.moe/8y8nyd.mp4

**Comment by kingsman12212** [comment]
KK thx i will see

**Comment by kingsman12212** [comment]
![image](https://user-images.githubusercontent.com/80263858/123499032-60d1f680-d651-11eb-8b36-d25d7a8b5e4d.png)
one more error

**Comment by kingsman12212** [comment]
![image](https://user-images.githubusercontent.com/80263858/123499165-4b110100-d652-11eb-86b9-d0f1860c7379.png)
i fixed all of them but i cant use license page

**Comment by kingsman12212** [comment]
and how do i get owner perm in that

**Comment by wnelson03** [comment]
Set dayproduct to null too

**Comment by kingsman12212** [comment]
i did 
but i cant see license page its always blank 
![image](https://user-images.githubusercontent.com/80263858/123500095-1f454980-d659-11eb-8913-700e433d6f00.png)

**Comment by kingsman12212** [comment]
ok see i fixed the error now how do i use it like see i get this error how can i fix it 

![image](https://user-images.githubusercontent.com/80263858/123500400-70563d00-d65b-11eb-9dd4-3f6150ae69e9.png)

**Comment by kingsman12212** [comment]
i need apis were do i get them 
any suggestion?

**Comment by wnelson03** [comment]
https://yoursite.com/api/1.0/

**Comment by kingsman12212** [comment]
can u guys make a c++ source for a private keyauth for us ? (Like the one we got with api and stuff)

**Comment by wnelson03** [comment]
Yeah a .LIB file for c++ is coming in the future

**Comment by x0-GHOST-0x** [comment]
kinsman12212, how did you get rid of the blank "licenses" page?  All the other links on the side and ability to create an application work for me, but I still get a blank license page when loading.  Did all the changes and suggestions above as well.  Any help is appreciated.
