### ISSUE TITLE
Hello devs

### ISSUE THREAD

**Issue by kamrulHasan12** [KeyAuth/KeyAuth-Source-Code#31]
There's an issue with mange panel, while I'm trying to go to manage panel, my role automatic go back to tester.
Is it a bug or its unavailable on source 
Thank You

**Comment by wnelson03** [comment]
Go to the `accounts` table and find your account. Change the `role` column to `seller` and change the `expires` column to `315569260`. This number is the unix timestamp for 10 years from now. So, your account won't go back to tester for 10 years
