### ISSUE TITLE
Code all messed up

### ISSUE THREAD

**Issue by ItaHacker** [KeyAuth/KeyAuth-Source-Code#33]
On the file dashboard/app/licenses/index.php all code is messed up and is 1 line.
Is completly a mess.

**Comment by wnelson03** [comment]
Yeah not sure why it's like that for some files. I committed with GitHub desktop. When I download the entire repo, or view the file raw, it's not on one line. So I guess it doesn't matter that much, maybe it'll correct itself when I commit to that file next time.
