### ISSUE TITLE
Update not working 

### ISSUE THREAD

**Issue by CrzyBnana** [KeyAuth/KeyAuth-Source-Code#34]
Key when i try to update my database ALTER TABLE `apps` ADD `webdownload` varchar(120) DEFAULT NULL; this comes out can someone help me ?

**Comment by CrzyBnana** [comment]
its an error !

**Comment by mazk5145** [comment]
if you still have this issue, could you upload picture of that error to like Imgur and send that here.

**Comment by wnelson03** [comment]
No response, I'm going to close for now.
