### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by wertani2** [KeyAuth/KeyAuth-Source-Code#37]
admin won't login stack at the the logo

**Comment by wnelson03** [comment]
go to your database, then go to the accounts table, then change the column `admin` to `1` from `0` following this, you should no longer get logo at admin dashboard. However, if you don't have 2FA you will be required to turn it on. So your options are either to enable 2FA in account settings or remove lines 77-80 of the `/admin/index.php` file

**Comment by wertani2** [comment]
Thanks is resolved but when I login to admin panel I can't see the app created but when I tap in search with email I can find it 
Please fix it

**Comment by wnelson03** [comment]
the admin dashboard has nothing to do with managing apps. it's for managing accounts, so you can ban accounts or edit them and give them seller or developer subscription.
