### ISSUE TITLE
Json Hosting 

### ISSUE THREAD

**Issue by vynxcc** [KeyAuth/KeyAuth-Source-Code#39]
any shot yall could have a feature to store json with the ability to update and rate limit it, kind of like the variables but updateable?

**Comment by mazk5145** [comment]
i think this is suggestion please do this 
![image](https://user-images.githubusercontent.com/79049205/162023613-3a6fc9a4-581a-402b-ab1e-a621338438af.png)
![image](https://user-images.githubusercontent.com/79049205/162023636-f3d4d867-401a-46b6-b924-690ac6896eaf.png)

**Comment by wnelson03** [comment]
You can update variables https://docs.keyauth.win/seller/variables#edit-variable. If you wanted to update variable securely through app, you can use webhook function.

Also, you can do user-specific variables. There's examples of how get and set user variables in the example.

Let us know if this answers your inquiry.
