### ISSUE TITLE
Error message: Field 'sellixsecret' doesn't have a default value

### ISSUE THREAD

**Issue by SamuelBostock** [KeyAuth/KeyAuth-Source-Code#4]
This error appears when attempting to create an application with the default settings, on a fresh installation of the source and database

**Comment by wnelson03** [comment]
Click on apps, then click on structure, then go to sellixsecret and press change. Then click null and save.

Video: https://files.catbox.moe/8y8nyd.mp4

**Comment by wnelson03** [comment]
That should've fixed your issue
