### ISSUE TITLE
Make the keyauth discord bot autorole a certain sub tier?

### ISSUE THREAD

**Issue by xSute** [KeyAuth/KeyAuth-Source-Code#40]
For an example, make it autorole everyone that has a active License lvl 1 sub a certain role (decided by the owner of the server) 
and then autorole the role off the person when his / hers subs ends

**Comment by wnelson03** [comment]
You can develop your own bot to do this. What I recommend is having a custom field on Shoppy or Sellix (if you use either of those) for users to put their Discord ID, then you have Shoppy or Sellix send a request to a link on your website, and then you get the Discord ID from the custom fields it sends you in request, and make request to Discord API to give role to user.

We're not going to change the Discord bot to have this capability. The bot is only to be used by staff of KeyAuth customer's, not customers of KeyAuth customers
