### ISSUE TITLE
Add more customization to the Customer App Panel

### ISSUE THREAD

**Issue by NotSnakeSilent** [KeyAuth/KeyAuth-Source-Code#41]
Hello, you can add an MOTD, Discord server , etc, this its for having the web panel and the faq or etc in an same page

and this will give us more customization to our seller app panel

**Comment by wnelson03** [comment]
I'll make an example soon of a customer panel you can host on your own website.

**Comment by wnelson03** [comment]
Done 👍 

https://github.com/KeyAuth/Custom-Customer-Panel
