### ISSUE TITLE
Website Bug

### ISSUE THREAD

**Issue by TheAngyMuffin** [KeyAuth/KeyAuth-Source-Code#42]
On laptop its hard to navigate the panel id suggest a scroller bar to grab and scroll down :) just like the nav bar has but the main pages need it it to scroll to the bottom of settings etc..

**Comment by wnelson03** [comment]
Thanks for letting us know. I had no idea. I plan to release new design soon, then this will be fixed.

In the meantime you should just zoom out on the page and it won't be much an issue.
