### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by arp242** [KeyAuth/KeyAuth-Source-Code#46]
Over here it gets the IP address from various headers, without checking their values:
https://github.com/KeyAuth/KeyAuth-Source-Code/blob/284cf6713df3385c60b2b47228693fb12f015564/includes/api/shared/primary.php#L21

They're *expected* to be set to an IP address, but a client can set them to anything.

And this value is then used directly in the query over here:
https://github.com/KeyAuth/KeyAuth-Source-Code/blob/284cf6713df3385c60b2b47228693fb12f015564/login/index.php#L168-L172

This is an SQL injection.

There are perhaps (probably, even) others as well. In a quick look there are a number of places where it's not immediately clear if a value is safe or not, but I didn't check them all. For example that `$username` is "sanitized" a 100 lines higher up, so it should be good, but it's not at all obvious from looking just at the query, and it can easily be forgotten.

It's a much better idea to use SQL parameters; I haven't programmed PHP in a long time, so I don't know the exact library methods for this, but then your query and parameters are sent separately on the wire protocol to the database, e.g.:

    mysqli_param_query('insert into tbl (col1, col2) values (?, ?)', $foo, $bar);

And you never have to worry about escaping, double escaping, or anything, and it's always safe.

Also your escape function calls strip_tags(); this means the data I sent won't be inserted as-is. I see have a `chatmsgs` table; what if I send `The link tag in HTML is <a>` to someone? It's much better to escape data at the last moment (when you're outputting it in your template).

**Comment by wnelson03** [comment]
Thank you. I totally agree with you and the many other people who've suggested that I use prepared statements. I've just been too lazy to implement it yet.

Yes, it does remove tags currently. As you said, I should be using `htmlentities` func. I haven't gotten around to changing that yet either.

I appreciate your bug report, I've committed the fix and hope you have a good day.
