### ISSUE TITLE
extend users bug

### ISSUE THREAD

**Issue by xLamantine** [KeyAuth/KeyAuth-Source-Code#47]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
I wanted to add 2 days to the subscription for users using extend users function, but as a result, your service deleted all the subscriptions of my users*

i have subscription for 5 years but now my sub just deleted

**Screenshots**

in this screen u can see that i loggined in 50mins ago
![image](https://user-images.githubusercontent.com/45714660/162618909-9712c4aa-a254-4a79-8ba2-752fa0556c82.png)

![image](https://user-images.githubusercontent.com/45714660/162618923-618fd3ea-80b1-4db0-970c-a4c63021ab7d.png)
in this screen u can see that my subscribe is deleted

**Comment by wnelson03** [comment]
Sorry about that, I fixed the bug from occurring again. Please make a ticket in the Discord server and provide your username and app name.

Then I'll be able to download one of our daily database backups and find one where the users' subscriptions weren't fucked up, and I can revert just those subscriptions to their original expiry. Then after that you should be able to do extend once again and it'll work fine.

Let me know when you've created a ticket on Discord and please specify your Discord username if it varies greatly from your GitHub username.

**Comment by wnelson03** [comment]
No response for two days, I close.
