### ISSUE TITLE
Credit system 

### ISSUE THREAD

**Issue by vynxcc** [KeyAuth/KeyAuth-Source-Code#49]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
I think a user specific credit system would be cool. If the credits could be updated from the dashboard or even generate keys to add credit. It could just be an int.

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by wnelson03** [comment]
Personally I feel it's sus to keep money in KeyAuth. I'll do a poll soon and see what others think.

**Comment by wnelson03** [comment]
I talked with staff and they don't think it's a good idea. If you want to buy someone else a subscription, you can go directly to the product links and input their username:

Developer plan: https://shoppy.gg/product/qgw9zmQ
Seller plan: https://shoppy.gg/product/lEbrHGK

We also show warning a month before the user expires, so the user has plenty of time to renew. Their plan's expiry is also displayed in account settings, so they can see that and put it on their calendar.
