### ISSUE TITLE
Laravel Package

### ISSUE THREAD

**Issue by CSharpDaddy** [KeyAuth/KeyAuth-Source-Code#50]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
*Can you make a laravel package for easy integration? Or make a documentation for laravel apps*

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by wnelson03** [comment]
I have no experience with Laravel, so I wouldn't be ready to develop a Laravel example. And I don't think Laravel is widely used among KeyAuth users, so I don't have much incentive to look for someone else to develop a Laravel example. Maybe in the future, I've been told Laravel is good and may learn it one day.

In the meantime, I recommend you take inspiration from https://github.com/KeyAuth/KeyAuth-PHP-Example to make a Laravel example. Or you can view https://docs.keyauth.win/api
