### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by host6666** [KeyAuth/KeyAuth-Source-Code#51]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
i suggest to add Custom OWNERID so we dont have to keep going back 

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by wnelson03** [comment]
a customer ownerID so you don't have to keep copying in from account settings?

seems silly. You'll still need to copy the application secret. these credentials need to be unique so allowing customization in them doesn't make sense.

if you don't like the idea of copying and pasting your ownerID each time, I recommend you use something like https://www.autohotkey.com/ where you can make it such that when you do a keybind, it pastes your ownerID.
