### ISSUE TITLE
Keyauth for lua

### ISSUE THREAD

**Issue by ruskichris** [KeyAuth/KeyAuth-Source-Code#53]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
KeyAuth for Lua, if possible

**Screenshots**
not applicable

**Comment by wnelson03** [comment]
Why don't you see what you can do?

Using https://github.com/JakobGreen/lua-requests seems like a good idea. The code for requests is likely similar the code for requests here https://github.com/KeyAuth/KeyAuth-Python-Example/

If you could at least create the basic outline for the KeyAuth lua class, I could likely do the requests code if you can't figure it out. I'm not good with lua, so idk how to make a good class. Though I would assume I could figure out how to do the requests part in Lua as I somewhat understand the requests part in Python.
