### ISSUE TITLE
Session ip/hwid track

### ISSUE THREAD

**Issue by mikeeek** [KeyAuth/KeyAuth-Source-Code#54]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
*HWID/IP tracking of sessions (non authed and authed) in keyauth dashboard. Currently it will show session id and username but no more information. In attached screenshot you can see couple sessions with no information for me to tell who its coming from*

**Screenshots**
![unknown-8](https://user-images.githubusercontent.com/25991438/165164611-dc07f9ae-5e53-4f36-a0a4-25d1bddd6433.png)

**Comment by wnelson03** [comment]
I added IP address in this commit 2a938b5ece1f2626cb2ea455b35aa9596aaf9183

I'm not going to add HWID, as it would only show for logged in users as HWID is only sent in login/license/register functions. So, it would be quite redundant.
