### ISSUE TITLE
x86 library issue

### ISSUE THREAD

**Issue by mut1234** [KeyAuth/KeyAuth-Source-Code#56]
Build started...
1>------ Build started: Project: example, Configuration: Release Win32 ------
1>library_x86.lib(auth.obj) : error LNK2001: unresolved external symbol _curl_easy_perform
1>library_x86.lib(auth.obj) : error LNK2001: unresolved external symbol _curl_easy_init
1>library_x86.lib(auth.obj) : error LNK2001: unresolved external symbol _curl_easy_strerror
1>library_x86.lib(auth.obj) : error LNK2001: unresolved external symbol _curl_easy_setopt
1>C:\Users\Mustafa\Desktop\New folder (3)\KeyAuth-CPP-Example-main\Release\example.exe : fatal error LNK1120: 4 unresolved externals
1>Done building project "example.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
![image](https://user-images.githubusercontent.com/44782684/165953056-29106fc1-84fa-4d05-8bc0-5c899349ece5.png)

**Comment by wnelson03** [comment]
You need to install x86 curl library. Google how to install the curl x86 library if you need help doing that.

As this isn't a KeyAuth problem, though simply needing to install the curl x86 library, I'm now going to close this.
