### ISSUE TITLE
Public API/Secret Key

### ISSUE THREAD

**Issue by xenos1337** [KeyAuth/KeyAuth-Source-Code#58]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that** 
✅ Yes

**Describe the suggestion**
Some kind of "public" secret, ownerid, etc... like stripe and many more.
With a public key you could make an JavaScript/HTML and way more examples, and there will be no need to protect the keys since they're public and don't have many permissions.
Here is some kind of example
```html
<script>
$.getJSON("//keyauth.com/api/v2/?key=pub12345abcdef0000&func=login", function(json) {
    if (json.status == "success") {
        // login here
    }
});
</script>
```

**Comment by wnelson03** [comment]
What do people need to protect their secret and ownerID from? It's not a seller key that can manage the application and its users. I don't see how adding another key would change anything, that key would still have the permissions a secret and ownerID do.

**Comment by xenos1337** [comment]
I don't know, I thought the secret & ownerID were something private but an AIO key would be very nice easier to implement into applications

**Comment by wnelson03** [comment]
Yeah maybe in next API ver, it'll just be secret.
