### ISSUE TITLE
EDIT HWID AND FULL PAID SERVICE

### ISSUE THREAD

**Issue by pbmsystem** [KeyAuth/KeyAuth-Source-Code#60]
Please consider let the admin edit the user hwid so we can use other fingerprints. the user SID is to weak.

And please consider become a close source and full paid service for more protection.

**Comment by wnelson03** [comment]
You can use whatever HWID you want. You just change the value passed for the HWID field in the client-side example. We’re going to continue to use Windows SID, as it’s the best one I’m aware of for programs that spoof most other HWIDs to bypass games’ anti-cheats. Plus, it would screw up all prior users if I were to change HWID used.

Many cybersecurity experts consider open source more secure than closed source, so I disagree with your latter comment. However, we do plan to make the source code of new paid features cost money. It won’t be much, but perhaps it’ll serve as a roadblock for people who have no intentions to contribute to the project.
