### ISSUE TITLE
Python Example not working

### ISSUE THREAD

**Issue by sfx2me** [KeyAuth/KeyAuth-Source-Code#63]
Code not working
 In the Python Example in line 114 i get the error: 

Traceback (most recent call last):
  File "P:\KeyAuth-Python-Example-main\main.py", line 114, in <module>
    subs = keyauthapp.user_data.subscriptions ## Get all Subscription names, expiry, and timeleft
AttributeError: 'user_data_class' object has no attribute 'subscriptions'

Create a User

It should create a user, it does but it doesnt get the subscriptions

**Comment by wnelson03** [comment]
Fixed in [6cb1578](https://github.com/KeyAuth/KeyAuth-Python-Example/commit/6cb1578254c5c881c9c9d520b9e74b9a273601d9)

Thanks for letting us know!
