### ISSUE TITLE
Button save settings

### ISSUE THREAD

**Issue by KratosMiner** [KeyAuth/KeyAuth-Source-Code#64]
dashboard/app/settings/
When I press the save button in settings the changes are not taken into account
Trying on different browser is same 

Also is not possible install the panel here https://hostsailor.com cause got a blank page after log/register

**Comment by wnelson03** [comment]
Make sure you set database credentials in `/includes/connection.php`

Yes, KeyAuth source should work on any PHP web hosting.

If you're still getting errors after setting database credentials, I recommend you add the line `error_reporting(1);` in the code for the login/register page after the include statements and then view the login/register page again to see what error it produces. 

Though I'm pretty sure the setting that setting the database credentials will resolve the blank page issue.

**Comment by KratosMiner** [comment]
All work fine except this ^^

And for the hosting i not a noob i know how use>< all is ok your code not correct

**Comment by KratosMiner** [comment]
And for the button ? why closed the issue because is not resolved ????

**Comment by wnelson03** [comment]
My code works fine, I use it live on the website with nginx and I use it for testing locally on my computer with apache.

You should follow my steps above plus Google. The reason this issue is closed is because you're the only one having problems... Meaning you need to fix your configuration, it's not our code that's the problem.

**Comment by KratosMiner** [comment]
Man i use your panel since more 6 month , i know how use ^^ i told you the button 
Why google is your code not google code so is your problem
Got a plan here and see yourself ^^ https://clients.hostsailor.com/clientarea.php
Error on sanitanize , $M and more

**Comment by Luke050** [comment]
hi i can confirm that i have same issue  i have your solution onpremise everything works fine, i can login add license,app etc but when im at https://[mydomain.com]/[customlink]/dashboard/app/settings/ and when i click save then page is blank(gray) when i refresh or opne again above link settings changes are not aplied tried multiple time.

**Comment by KratosMiner** [comment]
> hi i can confirm that i have same issue i have your solution onpremise everything works fine, i can login add license,app etc but when im at https://[mydomain.com]/[customlink]/dashboard/app/settings/ and when i click save then page is blank(gray) when i refresh or opne again above link settings changes are not aplied tried multiple time.

He don't care he close all issue without fix ^^

**Comment by KratosMiner** [comment]
> My code works fine, I use it live on the website with nginx and I use it for testing locally on my computer with apache.
> 
> You should follow my steps above plus Google. The reason this issue is closed is because you're the only one having problems... Meaning you need to fix your configuration, it's not our code that's the problem.

Read Luke050 and see i not alone

**Comment by Luke050** [comment]
> > My code works fine, I use it live on the website with nginx and I use it for testing locally on my computer with apache.
> > You should follow my steps above plus Google. The reason this issue is closed is because you're the only one having problems... Meaning you need to fix your configuration, it's not our code that's the problem.
> 
> Read Luke050 and see i not alone

Yeah this issue is still there. I found a way to change settings anyway - you need to change values directly in database in app table

**Comment by KratosMiner** [comment]
> > > My code works fine, I use it live on the website with nginx and I use it for testing locally on my computer with apache.
> > > You should follow my steps above plus Google. The reason this issue is closed is because you're the only one having problems... Meaning you need to fix your configuration, it's not our code that's the problem.
> > 
> > 
> > Read Luke050 and see i not alone
> 
> Yeah this issue is still there. I found a way to change settings anyway - you need to change values directly in database in app table

What hosting you use ? me blazingfast

**Comment by Luke050** [comment]
> > > > My code works fine, I use it live on the website with nginx and I use it for testing locally on my computer with apache.
> > > > You should follow my steps above plus Google. The reason this issue is closed is because you're the only one having problems... Meaning you need to fix your configuration, it's not our code that's the problem.
> > > 
> > > 
> > > Read Luke050 and see i not alone
> > 
> > 
> > Yeah this issue is still there. I found a way to change settings anyway - you need to change values directly in database in app table
> 
> What hosting you use ? me blazingfast

Hosted on Google cloud

**Comment by KratosMiner** [comment]
@wnelson03  please check and fix , i told youi use your panel since more 6 month , i know how use , all fine except this and error on another hosting
