### ISSUE TITLE
ERROR: Could not connect. No such file or directory

### ISSUE THREAD

**Issue by barry-mcockiner** [KeyAuth/KeyAuth-Source-Code#65]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**

**Describe the bug**
*replace this text with description of bug*
i added all files to my site and it says cannot find directory
**Steps To Reproduce**
*replace this text with steps to reproduce bug*
i just followed your steps. i cant access dashboard or literally anything besides your homepage
**Expected behavior**
*replace this text with the intended result you're trying to get*

**Screenshots**
![image](https://user-images.githubusercontent.com/95534062/170834751-abb3a679-af19-4461-86d1-ace21908e5de.png)

**Comment by wnelson03** [comment]
You need to add your MySQL database credentials in the `/includes/connection.php`
