### ISSUE TITLE
User profile pictures

### ISSUE THREAD

**Issue by ApoIlos** [KeyAuth/KeyAuth-Source-Code#67]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
To have the ability to have custom profile pictures per application user(not keyauth as a whole). Yes ik variables are a thing but would be cool if it was all integrated in to the api

**Screenshots**
[https://prnt.sc/rGZHaAlaPtaF](url)

**Comment by wnelson03** [comment]
Use user variables. This is something that won't be integrated into the API. Imgur and other image uploaders don't allow commercial use, so any authentication systems that have profile pictures integrated into their API risk getting their server blocked by the Image uploader and all images uploaded from that server being blacklisted.

I also don't want to store images on the server's disk as image uploaders provide far better performance than we could. I could pay for a CDN to add images to though that's not cheap plus not many people use profile pictures, so I'd rather leave that up to users to implement themselves.
