### ISSUE TITLE
Button save settings

### ISSUE THREAD

**Issue by KratosMiner** [KeyAuth/KeyAuth-Source-Code#70]
dashboard/app/settings/
When I press the save button in settings the changes are not taken into account and nothing in the db
Trying on different browser is same

@Luke050 : https://github.com/Luke050 have same issue but you close all without check/fix ^^

https://github.com/KeyAuth/KeyAuth-Source-Code/issues/64

Also please check here : https://hostsailor.com/  your panel don't work , atm i need use another hosting

**Comment by wnelson03** [comment]
Works fine, this is an issue with your configuration. Closing this again, do not open another issue about this.

**Comment by Luke050** [comment]
> Works fine, this is an issue with your configuration. Closing this again, do not open another issue about this.

I have not seen such hopeless support for a long time.😂😂😂😂

**Comment by KratosMiner** [comment]
> Works fine, this is an issue with your configuration. Closing this again, do not open another issue about this.

Man please stop kiding with me , i use your panel since more 6 month i know how use my config is normal and working fine since your last update , i not alone stop fucking with me
On some hosting panel not work why ???

**Comment by Luke050** [comment]
Is there any option to debug this particular site. Because your answer does nothing.  Two people have already reported the problem

**Comment by KratosMiner** [comment]
> Is there any option to debug this particular site. Because your answer does nothing. Two people have already reported the problem

In connection.php put this 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

And see all error xD

**Comment by KratosMiner** [comment]
This commit work !!!! https://github.com/KeyAuth/KeyAuth-Source-Code/tree/1b6fc063809f514a732d4c1adb90fecd4d9f36da

**Comment by KratosMiner** [comment]
https://github.com/KeyAuth/KeyAuth-Source-Code/tree/e31b03441f6bef609e9d01850a7d58115ef6445f

Before you add custom domain all work fine so is not my bad !!!
This commit work , since is broken
