### ISSUE TITLE
Stop kidding

### ISSUE THREAD

**Issue by KratosMiner** [KeyAuth/KeyAuth-Source-Code#71]
https://github.com/KeyAuth/KeyAuth-Source-Code/tree/e31b03441f6bef609e9d01850a7d58115ef6445f
Is the last commit working fine

Before you add custom domain all work fine so is not my bad !!!
This commit work , since is broken

**Comment by wnelson03** [comment]
Alright after I commited 02fa71e3b232c222adceb8d8838f81386ec9dd48 it is working for me

https://user-images.githubusercontent.com/83034852/172018169-88b36fb6-8a67-42e2-849a-1e98b2e08054.mp4

Do not open another GitHub issue about this, or I'm going to block you. You can't just say something "doesn't work" and provide no error message or anything. I could've helped you far earlier if you hadn't been acting like a useless ape.

**Comment by wnelson03** [comment]
Also you don't seem to have starred the GitHub repo, please star now 🦧

**Comment by KratosMiner** [comment]
Jew , nigga nice see this don't worry got reported
