### ISSUE TITLE
Crash dll auth

### ISSUE THREAD

**Issue by Roseiit** [KeyAuth/KeyAuth-Source-Code#73]
int user_login_auth()
{
	KeyAuthApp.init();
}
crash

**Comment by mazk5145** [comment]
what do you mean by crash dll auth?=

**Comment by mazk5145** [comment]
And you should **not** use auth on DLL, since it will be easily detectable since it's little sus that dll makes web requests.
It is better to use loader what have login and that injects the dll to the game

**Comment by wnelson03** [comment]
KeyAuth doesn't help with issues outside of default example with no changes. and mazk makes a good point.
