### ISSUE TITLE
Import keys

### ISSUE THREAD

**Issue by Roseiit** [KeyAuth/KeyAuth-Source-Code#76]
![image](https://user-images.githubusercontent.com/95353650/172393814-3884e38a-7dc9-4705-a1c3-ae4d723f7ce2.png)
In this way, adding the key will only exist after the first one and all the following ones will not be added. Although the web page shows that it has been added, the management will say that the key does not exist.

**Comment by mazk5145** [comment]
Hello Roseliit Is this happening on [KeyAuth](https://keyauth.win) or in localhost version?

**Comment by Roseiit** [comment]
> 

keyauth

**Comment by Roseiit** [comment]
> Hello Roseliit Is this happening on [KeyAuth](https://keyauth.win) or in localhost version?

keyauth
