### ISSUE TITLE
use web hook

### ISSUE THREAD

**Issue by Roseiit** [KeyAuth/KeyAuth-Source-Code#79]
The key auth tells everyone that the developer's identity can use it, but it only has the key in the seller's settings. I didn't find where the developer's web hook key is. I searched for a long time.

**Comment by mazk5145** [comment]
What do you mean by "developer's web hook key" ?

what is that?

**Comment by wnelson03** [comment]
You don't need a seller key to use the webook function. You just go to https://keyauth.win/dashboard/app/webhooks/ and add webhook then call the function in loader. Example here https://github.com/KeyAuth/KeyAuth-CS-Example/blob/e1271c0f021382fefed83982b0afe3419a36f16d/Console/Program.cs#L163
