### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nullinghax** [KeyAuth/KeyAuth-Source-Code#80]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

instead of the title of the embed say `Log: text`, make it say the text that was sent to the request, so just `Program Executed`

**Screenshots**
-
![image](https://user-images.githubusercontent.com/107588666/174399528-5616b67b-6c5f-4795-95a1-5f248ac5cdd3.png)

**Comment by mazk5145** [comment]
Do you want it to just say the text not the `log + text`?

**Comment by mazk5145** [comment]
If so, and you are self hosting remove these lines from code

[1.1 API](https://github.com/KeyAuth/KeyAuth-Source-Code/blob/42075d66929ebf497acd9e0c3eddfa55e7df168f/api/1.1/index.php#L750) [1.0 API](https://github.com/KeyAuth/KeyAuth-Source-Code/blob/42075d66929ebf497acd9e0c3eddfa55e7df168f/api/1.0/index.php#L748)

^^ Those will redirect to the code that you need to remove,

But I will add this to the suggestion list and @wnelson03 and @Its-Networking  will take look to if it's good enchantment.

If you have any questions or etc please create a topic on [KeyAuth Forums](https://community.keyauth.win)





Best Regards
KeyAuth Head Admin / Developer - mazkdevf
