### ISSUE TITLE
Autohotkey supoort and example 

### ISSUE THREAD

**Issue by Lunnyishotlllll** [KeyAuth/KeyAuth-Source-Code#82]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
Autohotkey example 

**Screenshots**
If applicable, add screenshots to help illustrate your suggestion.

**Comment by mazk5145** [comment]
Hello [Lunh](https://github.com/Lunnyishotlllll),

I'm sure there is a fan-made example / some sort of login method on that on #code on our discord.
