### ISSUE TITLE
problem click on (Login or register) I get a 403 error

### ISSUE THREAD

**Issue by elunicoantivirus** [KeyAuth/KeyAuth-Source-Code#83]
I have a problem, in a clean server with mysql php and nginx I have copied the files of your project, then I have entered in the mysql database your sql file in a created database called main.

When entering the web it loads correctly but when I click on (Login or register) I get a 403 error that I suspect is because it does not connect to the database, could you please help me? Thank you.

My discord is = morenocompuestodebueno#6709

My phone is = +34685648587

I have whatsapp too.

**Comment by mazk5145** [comment]
Hello **[elunicoantivirus](https://github.com/elunicoantivirus)**,

Could you please give us link to your site, this could be caused because of **.htaccess** file
Please send us some screenshots of your hosting **PHP** Settings, if possible.

Best Regards
KeyAuth Head Admin / Developer - mazkdevf

**Comment by mazk5145** [comment]
Information Provided, htaccess file issue.
