### ISSUE TITLE
session doesnt expires

### ISSUE THREAD

**Issue by mainland1337** [KeyAuth/KeyAuth-Source-Code#84]
![image](https://user-images.githubusercontent.com/103630355/177136651-d05ffbea-0e4e-4cec-9d88-8c59c35959f3.png)
im setting up 30seconds, when im logging in the loader, waiting 30 seconds and then calling check session func, nothing happened, session is still alive. When i kill session from session in the dashboard then check session function gives me trigger.
![image](https://user-images.githubusercontent.com/103630355/177136926-ee70349c-9bcd-4b8d-8959-c399f3749425.png)
![image](https://user-images.githubusercontent.com/103630355/177136938-87464173-9274-4d6b-9cbb-4b88f0256b2b.png)

**Comment by mazk5145** [comment]
Hello **[mainland1337](https://github.com/mainland1337)** 

We will look into this, and keep you updated when we found the **solution** to this.

**Comment by mazk5145** [comment]
Oh yeah I found the issue, / It is not basically an issue but yeah

It will clear the sessions list after some KeyAuth function is executed and init is not one of those

**Comment by mazk5145** [comment]
This still can be easily fixable by adding this after `130 Line` on 1.0 and 1.1 api
^^ And that is the init call.

```
// Cleanup Sessions
mysqli_query($link, "DELETE FROM `sessions` WHERE `expiry` < " . time() . "");
```

**Comment by mazk5145** [comment]
Issue Solved / Solution Found.
