### ISSUE TITLE
Fetch one license with key

### ISSUE THREAD

**Issue by nishuzumi** [KeyAuth/KeyAuth-Source-Code#86]
**I understand this isn't for asking for help with an already existent feature. I must join https://keyauth.win/discord/ for help with that**

**Describe the suggestion**
Currently there is only one Fetch all licenses, can you add an api to fetch one license with key. e.g. https://keyauth.win/api/seller/?sellerkey=sellerkeyhere&type=fetchonekey &key=xxxx-xxxx-xxx.
The returned content is basically the same as Fetch all licenses, but only the value with the same key will be returned.

**Comment by mazk5145** [comment]
So do you want to fetch the key details or what ?

**Comment by mazk5145** [comment]
if that is so: `https://keyauth.win/api/seller/?sellerkey=sellerkeyhere&type=userdata&user=KeyHere` use that.

**Comment by nishuzumi** [comment]
I want to get the license duration, creation date, status, notes, etc.

**Comment by mazk5145** [comment]
> I want to get the license duration, create date, status, notes, etc.

Okay so use that link that i send you before it will return this
```
{"success":true,"username":"user","subscriptions":[{"subscription":"default","expiry":"1642968815","timeleft":2588179},{"subscription":"default","expiry":"1671913200","timeleft":31532564},{"subscription":"default","expiry":"1671915000","timeleft":31534364}],"ip":"assaasas","hwid":"asassa","createdate":"1640379353","lastlogin":"1640373896"}
```

**Comment by nishuzumi** [comment]
Thanks

**Comment by mazk5145** [comment]
np
