### ISSUE TITLE
chat issue

### ISSUE THREAD

**Issue by Luke050** [KeyAuth/KeyAuth-Source-Code#89]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**

I think the problem is the query responsible for deleting all messages from the chat over 20:
```
DELETE FROM `chatmsgs` WHERE `app` = '$secret' AND `id` NOT IN ( SELECT `id` FROM ( SELECT `id` FROM `chatmsgs` WHERE `channel` = '$channel' AND `app` = '$secret' ORDER BY `id` DESC LIMIT 20) foo )
```
everything is ok if we have one channel and one user or one channel and several users in this channel. the problem arises when I send a message via another user to another channel. then all messages from that app will be deleted except the last one

so steps to reproduce is :
create user1 and send message to channel1
create user2 and send message to channel2
all messages except message from user2 will be deleted

also easy to reproduce if you have some messages in app  and perform this query using different channel. so you simulate sending message to another channel because it is performed every time when i send message:

![image](https://user-images.githubusercontent.com/27148900/180648242-63dc17bf-f170-49b3-b662-d8d18c3901d2.png)

all messages will be deleted

**Comment by wnelson03** [comment]
Fixed in update made today, thanks for letting us know.

**Comment by Luke050** [comment]
You are welcome,  can you share this fix  I'm not as good in SQL queries and want to fix that also on my end. I cant see any changes in github repo so probably only your production  was fixed 😅

**Comment by wnelson03** [comment]
https://github.com/KeyAuth/KeyAuth-Source-Code/blob/6530675ecc5624c01127e2f59559dd752f93ffb9/api/1.0/index.php#L725

**Comment by Luke050** [comment]
> https://github.com/KeyAuth/KeyAuth-Source-Code/blob/6530675ecc5624c01127e2f59559dd752f93ffb9/api/1.0/index.php#L725

but this is exacly same line as i mentioned,  so what has changed ?

**Comment by wnelson03** [comment]
> > https://github.com/KeyAuth/KeyAuth-Source-Code/blob/6530675ecc5624c01127e2f59559dd752f93ffb9/api/1.0/index.php#L725
> 
> but this is exacly same line as i mentioned, so what has changed ?

Quite easy to see if you use a comparison tool such as https://editor.mergely.com/

**Comment by Luke050** [comment]
Well I know that it is not same because I posted direct query for mysql and you mentioned line from API but it is same thing, I also didn't see any change in the API after I reported this problem.

**Comment by wnelson03** [comment]
Apologies, I had updated for 1.1 and 1.2 API endpoints but not 1.0. You can see difference in the commit I just made here 093339290609d2e05e8d1e02272d6bbfe340dd44

**Comment by Luke050** [comment]
> Apologies, I had updated for 1.1 and 1.2 API endpoints but not 1.0. You can see difference in the commit I just made here [0933392](https://github.com/KeyAuth/KeyAuth-Source-Code/commit/093339290609d2e05e8d1e02272d6bbfe340dd44)

👍 Thanks this is it! 😊
