### ISSUE TITLE
lorem impsum issue

### ISSUE THREAD

**Issue by rolkoztm** [KeyAuth/KeyAuth-Source-Code#90]
![image](https://user-images.githubusercontent.com/60612933/182349447-870db9f1-d5fc-4476-a0b0-f5afd49eda59.png)
delete lorem impsum

**Comment by mazk5145** [comment]
Hello rolkoztm, Thanks for reporting this bug/loremthing to us, we will take look soon as possible to fix the issue. 

Best Regards
KeyAuth Head Admin / Developer mazkdevf.
