### ISSUE TITLE
Customer Panel Redirection Failed

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#91]
![image](https://user-images.githubusercontent.com/72171280/182353135-c2f86551-e644-4976-a0a7-e3de0293c44f.png)

If i login in the customer panel i get a redirection error ERR_TOO_MANY_REDIRECTS

(I think the redirection is again false, its here https://keyauth.cc/panel/{APPLICATION}/dashboard/ but must be https://keyauth.cc/panel/dashboard/)

+
The "Create-Account" Link is bugged too.

He send you to: https://keyauth.cc/panel/{APPLICATION}/register/
But its https://keyauth.cc/panel/register/

**Comment by mazk5145** [comment]
Hello Pinguu-dev, Thanks for reporting this bug to us, we will take look soon as possible to fix the issue. 

Best Regards
KeyAuth Head Admin / Developer mazkdevf.

**Comment by wnelson03** [comment]
Fixed. thanks for letting us know.
