### ISSUE TITLE
2FA Doesn't work. (keyauth.cc/login)

### ISSUE THREAD

**Issue by mazk5145** [KeyAuth/KeyAuth-Source-Code#93]
**I understand this isn't for asking for help with an already existent feature OR an error with compiling an example. I must join https://keyauth.win/discord/ for help with that**
yes :D

**Describe the bug**
*replace this text with description of bug*
2FA Field is not needed to be filled while account have the 2FA Enabled

**Video**
If applicable, add screenshots / videos to help explain your problem.
https://streamable.com/9k8dsn

**Comment by wnelson03** [comment]
Ik it only comes up when new login location now.
