### ISSUE TITLE
Visual error user filter

### ISSUE THREAD

**Issue by McDriven83** [KeyAuth/KeyAuth-Source-Code#97]
I wanted to point out that when you use the user filter to search for a user then pressing the actions key many options remain hidden and cannot be used.
I attach photos
![error keyauth](https://user-images.githubusercontent.com/101823416/182849605-06647300-f943-4e25-bdf4-1bf65a37c757.PNG)

**Comment by mazk5145** [comment]
Hello **[McDriven83](https://github.com/McDriven83)** 

I have fixed that issue, i just need to contact founder to change them in host.

**Comment by mazk5145** [comment]
Fixed to Dev Branch & also Will be updated to **https://keyauth.win - https://keyauth.cc** as soon as 
KeyAuth Founder is home.
