### ISSUE TITLE
Can't refresh my owner id

### ISSUE THREAD

**Issue by Pinguu-dev** [KeyAuth/KeyAuth-Source-Code#98]
Hey there!

I can't refresh my owner id - I saw no buttons for it but in your source code it still exist
https://github.com/KeyAuth/KeyAuth-Source-Code/blob/ba83f4f0f76e632812149c739f1c59922b098a68/dashboard/account/settings/index.php#L614

![image](https://user-images.githubusercontent.com/72171280/183089203-b23152b1-fbe7-4553-b2d0-13095d6c0490.png)

**Comment by mazk5145** [comment]
Oh thanks, we will look into it

**Comment by mazk5145** [comment]
> I can't refresh my owner id - I saw no buttons for it but in your source code it still exists

It doens't, the main branch is not yet updated to the latest dashboard, and we will probably do like email/username change: ownerid change.

**Comment by wnelson03** [comment]
Yeah I've yet to update main branch with source yet. In the latest update, I removed the refresh OwnerID. There's no need for it, it doesn't do any good to refresh your OwnerID so I removed that.

I will merge dev branch into main branch soon.

**Comment by Pinguu-dev** [comment]
> Yeah I've yet to update main branch with source yet. In the latest update, I removed the refresh OwnerID. There's no need for it, it doesn't do any good to refresh your OwnerID so I removed that.
> 
> I will merge dev branch into main branch soon.

Sometimes i refreshed to owner id to make the application again unique because you need provide the owner id - But i readded it in my self hosting.
