### ISSUE TITLE
hwid

### ISSUE THREAD

**Issue by Roseiit** [KeyAuth/KeyAuth-Source-Code#99]
Set hwid cooldown to 0 user still locked out

**Comment by mazk5145** [comment]
🤔, can you provide more info, doesn't help much if you just say doesn't work.

**Comment by Roseiit** [comment]
When i adjust the settings in the web page to 0 hwid and 0 seconds my user still has hwid it doesn't reset the hwid auto

**Comment by mazk5145** [comment]
![image](https://user-images.githubusercontent.com/79049205/183250735-ceb67404-ec51-4853-9084-b26c78466469.png)

Yeah if you are talking about that, that is not an automatical reset. It is made for Customer Panel resetting. If you want to create your automatic reset then you will have to use seller plan and create a bot or smth running that automatically resets when the time is.
